name: Build wheels

on:
  release:
    types:
      - created

env:
  BLASTDB: blast-db
  CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux_2_24_x86_64
  CIBW_MANYLINUX_I686_IMAGE: quay.io/pypa/manylinux_2_24_i686
  CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux_2_24_aarch64

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    timeout-minutes: 20
    env:
      CIBW_SKIP: "cp27-* pp*"
      CIBW_BEFORE_BUILD: "pip install cython"
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.7"
      - name: Install build dependencies
        run: python -m pip install cibuildwheel==1.10.0 cython==0.29.22 wheel
      - name: Build wheels
        run: |
          make build-vendored-deps
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          name: wheels-${{github.event.release.tag_name}}
          path: ./wheelhouse/*.whl
