name: Build wheels

#on: release
on: push

env:
  BLASTDB: blast-db
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    timeout-minutes: 20
    env:
      CIBW_SKIP: "cp27-* pp27-*"
      CIBW_BEFORE_BUILD: "pip install cython"
    strategy:
      matrix:
        # Ubuntu 18.04 is required because the 20.04 toolchain is too new for the "manylinux1_x86_64" ABI
        os: [ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.7"
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.10.0 cython==0.29.22 wheel
      - name: Build wheels
        run: |
          make build-vendored-deps
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
